FROM node:22-alpine
WORKDIR /app
ENV NODE_ENV=production

RUN mkdir -p /app/data
COPY cron.js ./
RUN npm init -y && npm install --no-package-lock croner@9.0.0 cryptr@6.4.0 dotenv@16.0.3

CMD ["node", "cron.js"]
