/** @type {import('tailwindcss').Config} */
module.exports = {
   content: [
      './pages/**/*.{js,ts,jsx,tsx}',
      './components/**/*.{js,ts,jsx,tsx}',
   ],
   safelist: [
      'max-h-48',
      'w-[150px]',
      'w-[240px]',
      'min-w-[270px]',
      'min-w-[180px]',
      'max-w-[180px]',
    ],
   theme: {
      extend: {
         fontFamily: {
            primary: ['Inter Variable', 'Inter', 'Arial', 'sans-serif'],
         },
         fontSize: {
            'ds-xs': 'var(--font-size-xs)',
            'ds-sm': 'var(--font-size-sm)',
            'ds-md': 'var(--font-size-md)',
            'ds-lg': 'var(--font-size-lg)',
            'ds-xl': 'var(--font-size-xl)',
            'ds-2xl': 'var(--font-size-2xl)',
            'ds-3xl': 'var(--font-size-3xl)',
            'ds-4xl': 'var(--font-size-4xl)',
            /* Light design-system font sizes */
            'md': ['0.875rem', { lineHeight: '1.25rem' }],
         },
         colors: {
            'surface-base': 'var(--color-surface-base)',
            'surface-strong': 'var(--color-surface-strong)',
            'surface-raised': 'var(--color-surface-raised)',
            'text-primary': 'var(--color-text-primary)',
            'text-tertiary': 'var(--color-text-tertiary)',
            'border-strong': 'var(--color-border-strong)',
            /* Light design-system tokens */
            'white-base': 'var(--white-base)',
            'gray-10': 'var(--gray-10)',
            'gray-20': 'var(--gray-20)',
            'gray-40': 'var(--gray-40)',
            'gray-60': 'var(--gray-60)',
            'gray-100': 'var(--gray-100)',
            'gray-120': 'var(--gray-120)',
            'gray-140': 'var(--gray-140)',
            'gray-160': 'var(--gray-160)',
            'gray-base': 'var(--gray-base)',
            'purple-40': 'var(--purple-40)',
            'purple-base': 'var(--purple-base)',
            'purple-100': 'var(--purple-100)',
            'gray-5': 'var(--gray-5)',
            'green-60': 'var(--green-60)',
            'yellow-60': 'var(--yellow-60)',
            'red-60': 'var(--red-60)',
         },
         borderRadius: {
            'ds-xs': 'var(--radius-xs)',
            'ds-sm': 'var(--radius-sm)',
            'ds-md': 'var(--radius-md)',
            'ds-lg': 'var(--radius-lg)',
            'ds-xl': 'var(--radius-xl)',
         },
         spacing: {
            'ds-1': 'var(--space-1)',
            'ds-2': 'var(--space-2)',
            'ds-3': 'var(--space-3)',
            'ds-4': 'var(--space-4)',
            'ds-5': 'var(--space-5)',
            'ds-6': 'var(--space-6)',
            'ds-7': 'var(--space-7)',
            'ds-8': 'var(--space-8)',
            /* Light design-system spacing */
            '3xs': '0.125rem',
            '2xs': '0.25rem',
            'xs': '0.375rem',
            'sm': '0.5rem',
            'md': '0.75rem',
            'base': '1rem',
            'lg': '1.5rem',
            'xl': '2rem',
            '2xl': '2.5rem',
         },
         boxShadow: {
            'ds-1': 'var(--shadow-1)',
            'ds-2': 'var(--shadow-2)',
         },
         transitionDuration: {
            instant: 'var(--motion-instant)',
            fast: 'var(--motion-fast)',
            normal: 'var(--motion-normal)',
            slow: 'var(--motion-slow)',
         },
      },
   },
   plugins: [],
 };
