/** Self-hosted DigitX marketing assets (generated by scripts/download-digitx-assets.mjs) */
export const digitxAssets = {
  "logo": "/marketing/digitx/logo-2aa19d8a.png",
  "heroPattern": "/marketing/digitx/heroPattern-c317a0b6.png",
  "heroDx": "/marketing/digitx/heroDx-4bf6500b.png",
  "heroVector": "/marketing/digitx/heroVector-caed80bd.png",
  "arrowIcon": "/marketing/digitx/arrowIcon-4722ff81.png",
  "reasonIcons": [
    "/marketing/digitx/reasonIcons0-7e987449.png",
    "/marketing/digitx/reasonIcons1-e6e3c47b.png",
    "/marketing/digitx/reasonIcons2-0f5c5612.png",
    "/marketing/digitx/reasonIcons3-95f2f832.png",
    "/marketing/digitx/reasonIcons4-7ce1095d.png",
    "/marketing/digitx/reasonIcons5-c8ec8817.png"
  ],
  "serviceCardBg": "/marketing/digitx/serviceCardBg-d528c86f.png",
  "serviceAbstract": "/marketing/digitx/serviceAbstract-e18f81eb.png",
  "serviceAbstractAlt": "/marketing/digitx/serviceAbstractAlt-21d8b6d9.png",
  "serviceIcons": [
    "/marketing/digitx/serviceIcons0-d9e9cafd.png",
    "/marketing/digitx/serviceIcons1-0bfb7117.png",
    "/marketing/digitx/serviceIcons2-eb39d962.png",
    "/marketing/digitx/serviceIcons3-fd841426.png"
  ],
  "serviceArrow": "/marketing/digitx/serviceArrow-cef57e57.png",
  "testimonialBg": "/marketing/digitx/testimonialBg-d27765f1.png",
  "testimonialQuote": "/marketing/digitx/testimonialQuote-d375b18a.png",
  "testimonialTail": "/marketing/digitx/testimonialTail-6e4a8230.png",
  "testimonialAvatars": [
    "/marketing/digitx/testimonialAvatars0-ff168958.png",
    "/marketing/digitx/testimonialAvatars1-4c8bec39.png",
    "/marketing/digitx/testimonialAvatars2-e4120222.png",
    "/marketing/digitx/testimonialAvatars3-ba22c631.png"
  ],
  "ctaBg": "/marketing/digitx/ctaBg-255954cb.png",
  "ctaAbstractLeft": "/marketing/digitx/ctaAbstractLeft-28fb260b.png",
  "ctaAbstractRight": "/marketing/digitx/ctaAbstractRight-ca481e9e.png",
  "ctaLogo": "/marketing/digitx/ctaLogo-e0a9374b.png",
  "footerLogo": "/marketing/digitx/footerLogo-ad96d164.png",
  "socialLinkedin": "/marketing/digitx/socialLinkedin-2b83a30b.png",
  "socialInstagram": "/marketing/digitx/socialInstagram-6dcd5e93.png",
  "socialTwitter": "/marketing/digitx/socialTwitter-ffc20ac4.png"
} as const;
