export type SetupLocation = { country: string; language: string; code: string; flag: string };

/** Country + language options for the workspace creator. `code` is the language
 * code passed to /api/domains/configure (which SERP/content generation use). */
export const SETUP_LOCATIONS: SetupLocation[] = [
   { country: 'Poland', language: 'Polish', code: 'pl', flag: '🇵🇱' },
   { country: 'Poland', language: 'English', code: 'en', flag: '🇵🇱' },
   { country: 'United States', language: 'English', code: 'en', flag: '🇺🇸' },
   { country: 'United Kingdom', language: 'English', code: 'en', flag: '🇬🇧' },
   { country: 'Germany', language: 'German', code: 'de', flag: '🇩🇪' },
   { country: 'France', language: 'French', code: 'fr', flag: '🇫🇷' },
   { country: 'France', language: 'English', code: 'en', flag: '🇫🇷' },
   { country: 'Spain', language: 'Spanish', code: 'es', flag: '🇪🇸' },
   { country: 'Italy', language: 'Italian', code: 'it', flag: '🇮🇹' },
   { country: 'Brazil', language: 'Brazilian Portuguese', code: 'pt', flag: '🇧🇷' },
   { country: 'Brazil', language: 'English', code: 'en', flag: '🇧🇷' },
   { country: 'Portugal', language: 'Portuguese', code: 'pt', flag: '🇵🇹' },
   { country: 'Netherlands', language: 'Dutch', code: 'nl', flag: '🇳🇱' },
   { country: 'Belgium', language: 'Dutch', code: 'nl', flag: '🇧🇪' },
   { country: 'Belgium', language: 'French', code: 'fr', flag: '🇧🇪' },
   { country: 'Sweden', language: 'Swedish', code: 'sv', flag: '🇸🇪' },
   { country: 'Norway', language: 'Norwegian', code: 'no', flag: '🇳🇴' },
   { country: 'Denmark', language: 'Danish', code: 'da', flag: '🇩🇰' },
   { country: 'Finland', language: 'Finnish', code: 'fi', flag: '🇫🇮' },
   { country: 'Czech Republic', language: 'Czech', code: 'cs', flag: '🇨🇿' },
   { country: 'Slovakia', language: 'Slovak', code: 'sk', flag: '🇸🇰' },
   { country: 'Ukraine', language: 'Ukrainian', code: 'uk', flag: '🇺🇦' },
   { country: 'Romania', language: 'Romanian', code: 'ro', flag: '🇷🇴' },
   { country: 'Hungary', language: 'Hungarian', code: 'hu', flag: '🇭🇺' },
   { country: 'Austria', language: 'German', code: 'de', flag: '🇦🇹' },
   { country: 'Switzerland', language: 'German', code: 'de', flag: '🇨🇭' },
   { country: 'Ireland', language: 'English', code: 'en', flag: '🇮🇪' },
   { country: 'Canada', language: 'English', code: 'en', flag: '🇨🇦' },
   { country: 'Canada', language: 'French', code: 'fr', flag: '🇨🇦' },
   { country: 'Australia', language: 'English', code: 'en', flag: '🇦🇺' },
   { country: 'Mexico', language: 'Spanish', code: 'es', flag: '🇲🇽' },
   { country: 'Argentina', language: 'Spanish', code: 'es', flag: '🇦🇷' },
   { country: 'Turkey', language: 'Turkish', code: 'tr', flag: '🇹🇷' },
   { country: 'Greece', language: 'Greek', code: 'el', flag: '🇬🇷' },
   { country: 'India', language: 'English', code: 'en', flag: '🇮🇳' },
   { country: 'Japan', language: 'Japanese', code: 'ja', flag: '🇯🇵' },
];
