export type SetupLocation = { country: string; language: string; code: string; cc: string };

/** Country + language options for the workspace creator. `code` is the language
 * code passed to /api/domains/configure; `cc` is the ISO-3166 alpha-2 country
 * code used for the flag image (cdn.jsdelivr.net/npm/flag-icons/flags/4x3/<cc>.svg). */
export const SETUP_LOCATIONS: SetupLocation[] = [
   { country: 'Poland', language: 'Polish', code: 'pl', cc: 'pl' },
   { country: 'Poland', language: 'English', code: 'en', cc: 'pl' },
   { country: 'United States', language: 'English', code: 'en', cc: 'us' },
   { country: 'United Kingdom', language: 'English', code: 'en', cc: 'gb' },
   { country: 'Germany', language: 'German', code: 'de', cc: 'de' },
   { country: 'France', language: 'French', code: 'fr', cc: 'fr' },
   { country: 'France', language: 'English', code: 'en', cc: 'fr' },
   { country: 'Spain', language: 'Spanish', code: 'es', cc: 'es' },
   { country: 'Italy', language: 'Italian', code: 'it', cc: 'it' },
   { country: 'Brazil', language: 'Brazilian Portuguese', code: 'pt', cc: 'br' },
   { country: 'Brazil', language: 'English', code: 'en', cc: 'br' },
   { country: 'Portugal', language: 'Portuguese', code: 'pt', cc: 'pt' },
   { country: 'Netherlands', language: 'Dutch', code: 'nl', cc: 'nl' },
   { country: 'Belgium', language: 'Dutch', code: 'nl', cc: 'be' },
   { country: 'Belgium', language: 'French', code: 'fr', cc: 'be' },
   { country: 'Sweden', language: 'Swedish', code: 'sv', cc: 'se' },
   { country: 'Norway', language: 'Norwegian', code: 'no', cc: 'no' },
   { country: 'Denmark', language: 'Danish', code: 'da', cc: 'dk' },
   { country: 'Finland', language: 'Finnish', code: 'fi', cc: 'fi' },
   { country: 'Czech Republic', language: 'Czech', code: 'cs', cc: 'cz' },
   { country: 'Slovakia', language: 'Slovak', code: 'sk', cc: 'sk' },
   { country: 'Ukraine', language: 'Ukrainian', code: 'uk', cc: 'ua' },
   { country: 'Romania', language: 'Romanian', code: 'ro', cc: 'ro' },
   { country: 'Hungary', language: 'Hungarian', code: 'hu', cc: 'hu' },
   { country: 'Austria', language: 'German', code: 'de', cc: 'at' },
   { country: 'Switzerland', language: 'German', code: 'de', cc: 'ch' },
   { country: 'Ireland', language: 'English', code: 'en', cc: 'ie' },
   { country: 'Canada', language: 'English', code: 'en', cc: 'ca' },
   { country: 'Canada', language: 'French', code: 'fr', cc: 'ca' },
   { country: 'Australia', language: 'English', code: 'en', cc: 'au' },
   { country: 'Mexico', language: 'Spanish', code: 'es', cc: 'mx' },
   { country: 'Argentina', language: 'Spanish', code: 'es', cc: 'ar' },
   { country: 'Turkey', language: 'Turkish', code: 'tr', cc: 'tr' },
   { country: 'Greece', language: 'Greek', code: 'el', cc: 'gr' },
   { country: 'India', language: 'English', code: 'en', cc: 'in' },
   { country: 'Japan', language: 'Japanese', code: 'ja', cc: 'jp' },
];
