/**
 * Country code -> [display/SERP name, hl language code, Google Ads geo target constant].
 *
 * The name is a wire value: the SERP providers in scrapers/services take it verbatim,
 * and it does NOT always match Intl.DisplayNames (e.g. 'Czech Republic', 'Turkey').
 */
/**
 * Country code -> [display/SERP name, hl language code, Google Ads geo target constant].
 *
 * The name is a wire value: the SERP providers in scrapers/services take it verbatim,
 * and it does NOT always match Intl.DisplayNames (e.g. 'Czech Republic', 'Turkey').
 */
const countries: countryData = {
   AD: ['Andorra', 'ca', 2020],
   AE: ['United Arab Emirates', 'ar', 2784],
   AF: ['Afghanistan', 'ps', 2004],
   AG: ['Antigua and Barbuda', 'en', 2028],
   AI: ['Anguilla', 'en', 0],
   AL: ['Albania', 'sq', 2008],
   AM: ['Armenia', 'hy', 2051],
   AO: ['Angola', 'pt', 2024],
   AQ: ['Antarctica', '', 2010],
   AR: ['Argentina', 'es', 2032],
   AS: ['American Samoa', 'en', 2016],
   AT: ['Austria', 'de', 2040],
   AU: ['Australia', 'en', 2036],
   AW: ['Aruba', 'nl', 0],
   AX: ['Åland', 'sv', 0],
   AZ: ['Azerbaijan', 'az', 2031],
   BA: ['Bosnia and Herzegovina', 'bs', 2070],
   BB: ['Barbados', 'en', 2052],
   BD: ['Bangladesh', 'bn', 2050],
   BE: ['Belgium', 'nl', 2056],
   BF: ['Burkina Faso', 'fr', 2854],
   BG: ['Bulgaria', 'bg', 2100],
   BH: ['Bahrain', 'ar', 2048],
   BI: ['Burundi', 'fr', 2108],
   BJ: ['Benin', 'fr', 2204],
   BL: ['Saint Barthélemy', 'fr', 2652],
   BM: ['Bermuda', 'en', 0],
   BN: ['Brunei', 'ms', 2096],
   BO: ['Bolivia', 'es', 2068],
   BQ: ['Bonaire', 'nl', 2535],
   BR: ['Brazil', 'pt', 2076],
   BS: ['Bahamas', 'en', 2044],
   BT: ['Bhutan', 'dz', 2064],
   BV: ['Bouvet Island', 'no', 0],
   BW: ['Botswana', 'en', 2072],
   BY: ['Belarus', 'be', 2112],
   BZ: ['Belize', 'en', 2084],
   CA: ['Canada', 'en', 2124],
   CC: ['Cocos [Keeling] Islands', 'en', 2166],
   CD: ['Democratic Republic of the Congo', 'fr', 2180],
   CF: ['Central African Republic', 'fr', 2140],
   CG: ['Republic of the Congo', 'fr', 2178],
   CH: ['Switzerland', 'de', 2756],
   CI: ['Ivory Coast', 'fr', 2384],
   CK: ['Cook Islands', 'en', 2184],
   CL: ['Chile', 'es', 2152],
   CM: ['Cameroon', 'en', 2120],
   CN: ['China', 'zh', 2156],
   CO: ['Colombia', 'es', 2170],
   CR: ['Costa Rica', 'es', 2188],
   CU: ['Cuba', 'es', 0],
   CV: ['Cape Verde', 'pt', 2132],
   CW: ['Curacao', 'nl', 2531],
   CX: ['Christmas Island', 'en', 2162],
   CY: ['Cyprus', 'el', 2196],
   CZ: ['Czech Republic', 'cs', 2203],
   DE: ['Germany', 'de', 2276],
   DJ: ['Djibouti', 'fr', 2262],
   DK: ['Denmark', 'da', 2208],
   DM: ['Dominica', 'en', 2212],
   DO: ['Dominican Republic', 'es', 2214],
   DZ: ['Algeria', 'ar', 2012],
   EC: ['Ecuador', 'es', 2218],
   EE: ['Estonia', 'et', 2233],
   EG: ['Egypt', 'ar', 2818],
   EH: ['Western Sahara', 'es', 0],
   ER: ['Eritrea', 'ti', 2232],
   ES: ['Spain', 'es', 2724],
   ET: ['Ethiopia', 'am', 2231],
   FI: ['Finland', 'fi', 2246],
   FJ: ['Fiji', 'en', 2242],
   FK: ['Falkland Islands', 'en', 0],
   FM: ['Micronesia', 'en', 2583],
   FO: ['Faroe Islands', 'fo', 0],
   FR: ['France', 'fr', 2250],
   GA: ['Gabon', 'fr', 2266],
   GB: ['United Kingdom', 'en', 2826],
   GD: ['Grenada', 'en', 2308],
   GE: ['Georgia', 'ka', 2268],
   GF: ['French Guiana', 'fr', 0],
   GG: ['Guernsey', 'en', 2831],
   GH: ['Ghana', 'en', 2288],
   GI: ['Gibraltar', 'en', 0],
   GL: ['Greenland', 'kl', 0],
   GM: ['Gambia', 'en', 2270],
   GN: ['Guinea', 'fr', 2324],
   GP: ['Guadeloupe', 'fr', 0],
   GQ: ['Equatorial Guinea', 'es', 2226],
   GR: ['Greece', 'el', 2300],
   GS: ['South Georgia and the South Sandwich Islands', 'en', 2239],
   GT: ['Guatemala', 'es', 2320],
   GU: ['Guam', 'en', 2316],
   GW: ['Guinea-Bissau', 'pt', 2624],
   GY: ['Guyana', 'en', 2328],
   HK: ['Hong Kong', 'zh', 0],
   HM: ['Heard Island and McDonald Islands', 'en', 2334],
   HN: ['Honduras', 'es', 2340],
   HR: ['Croatia', 'hr', 2191],
   HT: ['Haiti', 'fr', 2332],
   HU: ['Hungary', 'hu', 2348],
   ID: ['Indonesia', 'id', 2360],
   IE: ['Ireland', 'ga', 2372],
   IL: ['Israel', 'he', 2376],
   IM: ['Isle of Man', 'en', 2833],
   IN: ['India', 'hi', 2356],
   IO: ['British Indian Ocean Territory', 'en', 0],
   IQ: ['Iraq', 'ar', 2368],
   IR: ['Iran', 'fa', 0],
   IS: ['Iceland', 'is', 2352],
   IT: ['Italy', 'it', 2380],
   JE: ['Jersey', 'en', 2832],
   JM: ['Jamaica', 'en', 2388],
   JO: ['Jordan', 'ar', 2400],
   JP: ['Japan', 'ja', 2392],
   KE: ['Kenya', 'en', 2404],
   KG: ['Kyrgyzstan', 'ky', 2417],
   KH: ['Cambodia', 'km', 2116],
   KI: ['Kiribati', 'en', 2296],
   KM: ['Comoros', 'ar', 2174],
   KN: ['Saint Kitts and Nevis', 'en', 2659],
   KP: ['North Korea', 'ko', 0],
   KR: ['South Korea', 'ko', 2410],
   KW: ['Kuwait', 'ar', 2414],
   KY: ['Cayman Islands', 'en', 0],
   KZ: ['Kazakhstan', 'kk', 2398],
   LA: ['Laos', 'lo', 2418],
   LB: ['Lebanon', 'ar', 2422],
   LC: ['Saint Lucia', 'en', 2662],
   LI: ['Liechtenstein', 'de', 2438],
   LK: ['Sri Lanka', 'si', 2144],
   LR: ['Liberia', 'en', 2430],
   LS: ['Lesotho', 'en', 2426],
   LT: ['Lithuania', 'lt', 2440],
   LU: ['Luxembourg', 'fr', 2442],
   LV: ['Latvia', 'lv', 2428],
   LY: ['Libya', 'ar', 2434],
   MA: ['Morocco', 'ar', 2504],
   MC: ['Monaco', 'fr', 2492],
   MD: ['Moldova', 'ro', 2498],
   ME: ['Montenegro', 'sr', 2499],
   MF: ['Saint Martin', 'en', 2663],
   MG: ['Madagascar', 'fr', 2450],
   MH: ['Marshall Islands', 'en', 2584],
   MK: ['North Macedonia', 'mk', 2807],
   ML: ['Mali', 'fr', 2466],
   MM: ['Myanmar [Burma]', 'my', 2104],
   MN: ['Mongolia', 'mn', 2496],
   MO: ['Macao', 'zh', 0],
   MP: ['Northern Mariana Islands', 'en', 2580],
   MQ: ['Martinique', 'fr', 0],
   MR: ['Mauritania', 'ar', 2478],
   MS: ['Montserrat', 'en', 0],
   MT: ['Malta', 'mt', 2470],
   MU: ['Mauritius', 'en', 2480],
   MV: ['Maldives', 'dv', 2462],
   MW: ['Malawi', 'en', 2454],
   MX: ['Mexico', 'es', 2484],
   MY: ['Malaysia', 'ms', 2458],
   MZ: ['Mozambique', 'pt', 2508],
   NA: ['Namibia', 'en', 2516],
   NC: ['New Caledonia', 'fr', 2540],
   NE: ['Niger', 'fr', 2562],
   NF: ['Norfolk Island', 'en', 2574],
   NG: ['Nigeria', 'en', 2566],
   NI: ['Nicaragua', 'es', 2558],
   NL: ['Netherlands', 'nl', 2528],
   NO: ['Norway', 'no', 2578],
   NP: ['Nepal', 'ne', 2524],
   NR: ['Nauru', 'en', 2520],
   NU: ['Niue', 'en', 2570],
   NZ: ['New Zealand', 'en', 2554],
   OM: ['Oman', 'ar', 2512],
   PA: ['Panama', 'es', 2591],
   PE: ['Peru', 'es', 2604],
   PF: ['French Polynesia', 'fr', 2258],
   PG: ['Papua New Guinea', 'en', 2598],
   PH: ['Philippines', 'en', 2608],
   PK: ['Pakistan', 'en', 2586],
   PL: ['Poland', 'pl', 2616],
   PM: ['Saint Pierre and Miquelon', 'fr', 2666],
   PN: ['Pitcairn Islands', 'en', 2612],
   PR: ['Puerto Rico', 'es', 0],
   PS: ['Palestine', 'ar', 0],
   PT: ['Portugal', 'pt', 2620],
   PW: ['Palau', 'en', 2585],
   PY: ['Paraguay', 'es', 2600],
   QA: ['Qatar', 'ar', 2634],
   RE: ['Réunion', 'fr', 0],
   RO: ['Romania', 'ro', 2642],
   RS: ['Serbia', 'sr', 2688],
   RU: ['Russia', 'ru', 2643],
   RW: ['Rwanda', 'rw', 2646],
   SA: ['Saudi Arabia', 'ar', 2682],
   SB: ['Solomon Islands', 'en', 2090],
   SC: ['Seychelles', 'fr', 2690],
   SD: ['Sudan', 'ar', 2736],
   SE: ['Sweden', 'sv', 2752],
   SG: ['Singapore', 'en', 2702],
   SH: ['Saint Helena', 'en', 2654],
   SI: ['Slovenia', 'sl', 2705],
   SJ: ['Svalbard and Jan Mayen', 'no', 0],
   SK: ['Slovakia', 'sk', 2703],
   SL: ['Sierra Leone', 'en', 2694],
   SM: ['San Marino', 'it', 2674],
   SN: ['Senegal', 'fr', 2686],
   SO: ['Somalia', 'so', 2706],
   SR: ['Suriname', 'nl', 2740],
   SS: ['South Sudan', 'en', 2728],
   ST: ['São Tomé and Príncipe', 'pt', 2678],
   SV: ['El Salvador', 'es', 2222],
   SX: ['Sint Maarten', 'nl', 2534],
   SY: ['Syria', 'ar', 0],
   SZ: ['Swaziland', 'en', 2748],
   TC: ['Turks and Caicos Islands', 'en', 0],
   TD: ['Chad', 'fr', 2148],
   TF: ['French Southern Territories', 'fr', 2260],
   TG: ['Togo', 'fr', 2768],
   TH: ['Thailand', 'th', 2764],
   TJ: ['Tajikistan', 'tg', 2762],
   TK: ['Tokelau', 'en', 2772],
   TL: ['East Timor', 'pt', 2626],
   TM: ['Turkmenistan', 'tk', 2795],
   TN: ['Tunisia', 'ar', 2788],
   TO: ['Tonga', 'en', 2776],
   TR: ['Turkey', 'tr', 2792],
   TT: ['Trinidad and Tobago', 'en', 2780],
   TV: ['Tuvalu', 'en', 2798],
   TW: ['Taiwan', 'zh', 0],
   TZ: ['Tanzania', 'sw', 2834],
   UA: ['Ukraine', 'uk', 2804],
   UG: ['Uganda', 'en', 2800],
   UM: ['U.S. Minor Outlying Islands', 'en', 2581],
   US: ['United States', 'en', 2840],
   UY: ['Uruguay', 'es', 2858],
   UZ: ['Uzbekistan', 'uz', 2860],
   VA: ['Vatican City', 'it', 2336],
   VC: ['Saint Vincent and the Grenadines', 'en', 2670],
   VE: ['Venezuela', 'es', 2862],
   VG: ['British Virgin Islands', 'en', 0],
   VI: ['U.S. Virgin Islands', 'en', 0],
   VN: ['Vietnam', 'vi', 2704],
   VU: ['Vanuatu', 'bi', 2548],
   WF: ['Wallis and Futuna', 'fr', 2876],
   WS: ['Samoa', 'sm', 2882],
   XK: ['Kosovo', 'sq', 0],
   YE: ['Yemen', 'ar', 2887],
   YT: ['Mayotte', 'fr', 0],
   ZA: ['South Africa', 'af', 2710],
   ZM: ['Zambia', 'en', 2894],
   ZW: ['Zimbabwe', 'en', 2716],
   ZZ: ['Unknown', 'en', 0],
};

export const countryAlphaTwoCodes: countryCodeData = {
   AFG: 'AF',
   ALA: 'AX',
   ALB: 'AL',
   DZA: 'DZ',
   ASM: 'AS',
   AND: 'AD',
   AGO: 'AO',
   AIA: 'AI',
   ATA: 'AQ',
   ATG: 'AG',
   ARG: 'AR',
   ARM: 'AM',
   ABW: 'AW',
   AUS: 'AU',
   AUT: 'AT',
   AZE: 'AZ',
   BHS: 'BS',
   BHR: 'BH',
   BGD: 'BD',
   BRB: 'BB',
   BLR: 'BY',
   BEL: 'BE',
   BLZ: 'BZ',
   BEN: 'BJ',
   BMU: 'BM',
   BTN: 'BT',
   BOL: 'BO',
   BES: 'BQ',
   BIH: 'BA',
   BWA: 'BW',
   BVT: 'BV',
   BRA: 'BR',
   IOT: 'IO',
   BRN: 'BN',
   BGR: 'BG',
   BFA: 'BF',
   BDI: 'BI',
   CPV: 'CV',
   KHM: 'KH',
   CMR: 'CM',
   CAN: 'CA',
   CYM: 'KY',
   CAF: 'CF',
   TCD: 'TD',
   CHL: 'CL',
   CHN: 'CN',
   CXR: 'CX',
   CCK: 'CC',
   COL: 'CO',
   COM: 'KM',
   COG: 'CG',
   COD: 'CD',
   COK: 'CK',
   CRI: 'CR',
   CIV: 'CI',
   HRV: 'HR',
   CUB: 'CU',
   CUW: 'CW',
   CYP: 'CY',
   CZE: 'CZ',
   DNK: 'DK',
   DJI: 'DJ',
   DMA: 'DM',
   DOM: 'DO',
   ECU: 'EC',
   EGY: 'EG',
   SLV: 'SV',
   GNQ: 'GQ',
   ERI: 'ER',
   EST: 'EE',
   SWZ: 'SZ',
   ETH: 'ET',
   FLK: 'FK',
   FRO: 'FO',
   FJI: 'FJ',
   FIN: 'FI',
   FRA: 'FR',
   GUF: 'GF',
   PYF: 'PF',
   ATF: 'TF',
   GAB: 'GA',
   GMB: 'GM',
   GEO: 'GE',
   DEU: 'DE',
   GHA: 'GH',
   GIB: 'GI',
   GRC: 'GR',
   GRL: 'GL',
   GRD: 'GD',
   GLP: 'GP',
   GUM: 'GU',
   GTM: 'GT',
   GGY: 'GG',
   GIN: 'GN',
   GNB: 'GW',
   GUY: 'GY',
   HTI: 'HT',
   HMD: 'HM',
   VAT: 'VA',
   HND: 'HN',
   HKG: 'HK',
   HUN: 'HU',
   ISL: 'IS',
   IND: 'IN',
   IDN: 'ID',
   IRN: 'IR',
   IRQ: 'IQ',
   IRL: 'IE',
   IMN: 'IM',
   ISR: 'IL',
   ITA: 'IT',
   JAM: 'JM',
   JPN: 'JP',
   JEY: 'JE',
   JOR: 'JO',
   KAZ: 'KZ',
   KEN: 'KE',
   KIR: 'KI',
   PRK: 'KP',
   KOR: 'KR',
   KWT: 'KW',
   KGZ: 'KG',
   LAO: 'LA',
   LVA: 'LV',
   LBN: 'LB',
   LSO: 'LS',
   LBR: 'LR',
   LBY: 'LY',
   LIE: 'LI',
   LTU: 'LT',
   LUX: 'LU',
   MAC: 'MO',
   MDG: 'MG',
   MWI: 'MW',
   MYS: 'MY',
   MDV: 'MV',
   MLI: 'ML',
   MLT: 'MT',
   MHL: 'MH',
   MTQ: 'MQ',
   MRT: 'MR',
   MUS: 'MU',
   MYT: 'YT',
   MEX: 'MX',
   FSM: 'FM',
   MDA: 'MD',
   MCO: 'MC',
   MNG: 'MN',
   MNE: 'ME',
   MSR: 'MS',
   MAR: 'MA',
   MOZ: 'MZ',
   MMR: 'MM',
   NAM: 'NA',
   NRU: 'NR',
   NPL: 'NP',
   NLD: 'NL',
   NCL: 'NC',
   NZL: 'NZ',
   NIC: 'NI',
   NER: 'NE',
   NGA: 'NG',
   NIU: 'NU',
   NFK: 'NF',
   MKD: 'MK',
   MNP: 'MP',
   NOR: 'NO',
   OMN: 'OM',
   PAK: 'PK',
   PLW: 'PW',
   PSE: 'PS',
   PAN: 'PA',
   PNG: 'PG',
   PRY: 'PY',
   PER: 'PE',
   PHL: 'PH',
   PCN: 'PN',
   POL: 'PL',
   PRT: 'PT',
   PRI: 'PR',
   QAT: 'QA',
   REU: 'RE',
   ROU: 'RO',
   RUS: 'RU',
   RWA: 'RW',
   BLM: 'BL',
   SHN: 'SH',
   KNA: 'KN',
   LCA: 'LC',
   MAF: 'MF',
   SPM: 'PM',
   VCT: 'VC',
   WSM: 'WS',
   SMR: 'SM',
   STP: 'ST',
   SAU: 'SA',
   SEN: 'SN',
   SRB: 'RS',
   SYC: 'SC',
   SLE: 'SL',
   SGP: 'SG',
   SXM: 'SX',
   SVK: 'SK',
   SVN: 'SI',
   SLB: 'SB',
   SOM: 'SO',
   ZAF: 'ZA',
   SGS: 'GS',
   SSD: 'SS',
   ESP: 'ES',
   LKA: 'LK',
   SDN: 'SD',
   SUR: 'SR',
   SJM: 'SJ',
   SWE: 'SE',
   CHE: 'CH',
   SYR: 'SY',
   TWN: 'TW',
   TJK: 'TJ',
   TZA: 'TZ',
   THA: 'TH',
   TLS: 'TL',
   TGO: 'TG',
   TKL: 'TK',
   TON: 'TO',
   TTO: 'TT',
   TUN: 'TN',
   TUR: 'TR',
   TKM: 'TM',
   TCA: 'TC',
   TUV: 'TV',
   UGA: 'UG',
   UKR: 'UA',
   ARE: 'AE',
   GBR: 'GB',
   USA: 'US',
   UMI: 'UM',
   URY: 'UY',
   UZB: 'UZ',
   VUT: 'VU',
   VEN: 'VE',
   VNM: 'VN',
   VGB: 'VG',
   VIR: 'VI',
   WLF: 'WF',
   ESH: 'EH',
   YEM: 'YE',
   ZMB: 'ZM',
   ZWE: 'ZW',
   ZZZ: 'ZZ',
};

export const adwordsLanguages: Record<number, string> = {
   1000: 'English',
   1001: 'German',
   1002: 'French',
   1003: 'Spanish',
   1004: 'Italian',
   1005: 'Japanese',
   1009: 'Danish',
   1010: 'Dutch',
   1011: 'Finnish',
   1012: 'Korean',
   1013: 'Norwegian',
   1014: 'Portuguese',
   1015: 'Swedish',
   1017: 'Chinese (simplified)',
   1018: 'Chinese (traditional)',
   1019: 'Arabic',
   1020: 'Bulgarian',
   1021: 'Czech',
   1022: 'Greek',
   1023: 'Hindi',
   1024: 'Hungarian',
   1025: 'Indonesian',
   1026: 'Icelandic',
   1027: 'Hebrew',
   1028: 'Latvian',
   1029: 'Lithuanian',
   1030: 'Polish',
   1031: 'Russian',
   1032: 'Romanian',
   1033: 'Slovak',
   1034: 'Slovenian',
   1035: 'Serbian',
   1036: 'Ukrainian',
   1037: 'Turkish',
   1038: 'Catalan',
   1039: 'Croatian',
   1040: 'Vietnamese',
   1041: 'Urdu',
   1042: 'Filipino',
   1043: 'Estonian',
   1044: 'Thai',
   1056: 'Bengali',
   1064: 'Persian',
   1072: 'Gujarati',
   1086: 'Kannada',
   1098: 'Malayalam',
   1101: 'Marathi',
   1102: 'Malay',
   1110: 'Punjabi',
   1130: 'Tamil',
   1131: 'Telugu',
};

export const getCountryCodeFromAlphaThree = (AlphaThreeCode:string): string => countryAlphaTwoCodes[AlphaThreeCode];

export default countries;
